[package]
name = "aldoria-client"
version = "0.1.0"
description = "Desktop client for Embers of Aldoria"
edition = "2024"

[lib]
name = "aldoria_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

