[package]
name = "aldoria-client"
version = "0.1.6"
description = "Desktop client for Embers of Aldoria"
edition = "2024"

[lib]
name = "aldoria_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[features]
default = []
friend-updater = ["dep:tauri-plugin-updater"]

[dependencies]
serde_json = "1"
tauri-plugin-updater = { version = "2", optional = true }
tauri = { version = "2", features = [] }

