// TIBIAGAME_V36_10_NATIVE_GAMEPLAY_CORE
// TIBIAGAME_V36_63_0_CONNECTION_ERRORS_COPPER_VEINS
// TIBIAGAME_V36_64_0_COMPACT_UI_ROOF_DEPTH
// TIBIAGAME_V36_64_1_TRUE_3D_ROOF_VOLUME
// TIBIAGAME_V36_64_2_ROOF_UV_EDGE_FIX
// TIBIAGAME_V36_65_0_MATERIAL_DEPTH_OCCLUDERS_BATTLE_TARGETING
// TIBIAGAME_V36_65_1_RENDER_BUDGET_STABLE_VISIBILITY
// TIBIAGAME_V36_66_0_TIBIA_ALIGNED_CAMERA
// TIBIAGAME_V36_66_1_TIBIA_CAMERA_PROPORTIONS
// TIBIAGAME_V36_66_2_SEALED_FLOORS_AND_ROOF_EAVES
// TIBIAGAME_V36_66_3_CLEAN_WALL_CORNERS_AND_ROOF_TRIM
// TIBIAGAME_V36_67_0_BATCHED_GRASS_TUFTS
// TIBIAGAME_V36_67_1_FINE_TAPERED_GRASS
// TIBIAGAME_V36_68_0_STABLE_OPAQUE_ROOFS
// TIBIAGAME_V36_68_1_BATCHED_TREE_GEOMETRY
// TIBIAGAME_V36_69_0_NEAR_FIELD_GRASS_DETAIL
// TIBIAGAME_V36_70_0_SINGLE_DRAW_TREES
// TIBIAGAME_V36_71_0_SINGLE_DRAW_CLIFFS
// TIBIAGAME_V36_72_0_SHARED_OCCLUDER_MATERIALS
// TIBIAGAME_V36_72_1_LOCAL_OCCLUDER_FADE
// TIBIAGAME_V36_73_0_INTERIOR_FRONT_WALL_CUTAWAY
// TIBIAGAME_V36_74_0_INTERACTIVE_INVENTORY_CHAT_SPELLS
// TIBIAGAME_V36_74_1_UI_QUERY_CONFLICT_FIX
// TIBIAGAME_V36_75_0_ACTION_STATUS_BARS
// TIBIAGAME_V36_76_0_HOUSE_LIGHT_STACK_DEPOT_CLARITY
// TIBIAGAME_V36_77_0_ROBUST_HOUSE_CUTAWAY_DEPOT_FLOW
pub const MIGRATION_VERSION: &str = "36.77.0";

#[allow(dead_code)]
pub fn client_version() -> String {
    format!(
        "{}-native-v{}",
        env!("CARGO_PKG_VERSION"),
        MIGRATION_VERSION,
    )
}

pub fn window_title() -> String {
    format!(
        "Embers of Aldoria — Native V{} Live World",
        MIGRATION_VERSION,
    )
}

pub fn native_release_version() -> &'static str {
    option_env!("ALDORIA_NATIVE_RELEASE_VERSION").unwrap_or("dev")
}
