// TIBIAGAME_V36_10_NATIVE_GAMEPLAY_CORE
// TIBIAGAME_V36_63_0_CONNECTION_ERRORS_COPPER_VEINS
// TIBIAGAME_V36_64_0_COMPACT_UI_ROOF_DEPTH
// TIBIAGAME_V36_64_1_TRUE_3D_ROOF_VOLUME
// TIBIAGAME_V36_64_2_ROOF_UV_EDGE_FIX
// TIBIAGAME_V36_65_0_MATERIAL_DEPTH_OCCLUDERS_BATTLE_TARGETING
// TIBIAGAME_V36_65_1_RENDER_BUDGET_STABLE_VISIBILITY
// TIBIAGAME_V36_66_0_TIBIA_ALIGNED_CAMERA
// TIBIAGAME_V36_66_1_TIBIA_CAMERA_PROPORTIONS
// TIBIAGAME_V36_66_2_SEALED_FLOORS_AND_ROOF_EAVES
// TIBIAGAME_V36_66_3_CLEAN_WALL_CORNERS_AND_ROOF_TRIM
pub const MIGRATION_VERSION: &str = "36.66.3";

#[allow(dead_code)]
pub fn client_version() -> String {
    format!(
        "{}-native-v{}",
        env!("CARGO_PKG_VERSION"),
        MIGRATION_VERSION,
    )
}

pub fn window_title() -> String {
    format!(
        "Embers of Aldoria — Native V{} Live World",
        MIGRATION_VERSION,
    )
}

pub fn native_release_version() -> &'static str {
    option_env!("ALDORIA_NATIVE_RELEASE_VERSION").unwrap_or("dev")
}
